Update getting-started.md
(node:40245) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/thigas/repo/desafio-lacrei/commitlint.config.js:1
export default { extends: ['@commitlint/config-conventional'] };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1383:18)
    at Module._compile (node:internal/modules/cjs/loader:1412:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at module.exports (/home/thigas/repo/desafio-lacrei/node_modules/import-fresh/index.js:32:59)
    at loadJsSync (/home/thigas/repo/desafio-lacrei/node_modules/cosmiconfig/dist/loaders.js:17:12) {
  filepath: '/home/thigas/repo/desafio-lacrei/commitlint.config.js'
}

Node.js v22.4.1
husky - commit-msg script failed (code 1)